import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import Header from "./_components/Header/Header";
import WrapperForSeesionProvider from "./_components/WrapperForSeesionProvider/WrapperForSeesionProvider";
import CartContextProvider from "./_context/cartContext";
import { getUserCart } from "@/api/services/Route.services";
import { CartResponse } from "@/api/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await getUserCart();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-full flex flex-col`}
      >
        <CartContextProvider res={res}>
          <WrapperForSeesionProvider>
            <Header />
            <Navbar />

            {children}
            <Toaster />
            <Footer />
          </WrapperForSeesionProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
